plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.147'
}

version = mod_version
group = 'com.kinetic.earstails'

base {
    archivesName = 'KineticEarsTails-1.21.1'
}

// Minecraft 1.21.1 + NeoForge требуют Java 21
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
            gameDirectory = project.file('run')
        }

        server {
            server()
            gameDirectory = project.file('run')
            programArgument '--nogui'
        }
    }

    mods {
        faradayears {
            sourceSet(sourceSets.main)
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : 'faradayears',
            'Specification-Vendor'    : 'Kinetic Ears & Tails contributors',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : 'Kinetic Ears & Tails contributors',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}
