org.gradle.jvmargs=-Xmx3G -Xms1G
org.gradle.daemon=false
org.gradle.parallel=true

mod_version=1.5.5
mod_id=faradayears
mod_name=Faraday Ears & Tail Customizer
mod_license=MIT

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.251
neo_version_range=[21.1,)
loader_version_range=[1,)
