modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/antonovichkorp1985-maker/faradayears/issues"

[[mods]]
modId="faradayears"
version="2.1.1"
displayName="Kinetic Ears & Tails"
displayURL="https://github.com/antonovichkorp1985-maker/faradayears"
authors="Kinetic Ears & Tails contributors"
description='''
Косметический мод для Minecraft 1.21.1 NeoForge с настраиваемыми 3D-ушами, физическими хвостами и редактором текстур.
Особенности:
 - Интерактивное GUI кастомизации по нажатию клавиши (по умолчанию 'V')
 - Пресеты: Огненные кисточки, Лис/Котик, Волк, Кролик, Кицунэ, Кот с бантом
 - Точная настройка размеров, углов поворота и смещения ушек и хвоста
 - Физический хвост (Verlet + PBD) с коллизиями о землю и блоки; 2 режима: Классика / Реалистичная скелетно-мышечная
 - Кастомная текстура 64x64 (единый лист ушек и хвоста) с пиксельным редактором в GUI и подсказкой зон
 - Синхронизация между игроками по сети (мультиплеер!)
'''

[[dependencies.faradayears]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.faradayears]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
